services:
  postgres:
    image: postgres:16
    container_name: musetub-postgres
    env_file:
      - .env.docker
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: musetub-redis
    ports:
      - "6380:6379"

  ipfs:
    image: ipfs/kubo:latest
    container_name: musetub-ipfs
    ports:
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs-data:/data/ipfs

volumes:
  postgres-data:
  ipfs-data:
